


graphs = {
    "Dembi Dollo": ["Gimbi", "Gambella"],
    "Gimbi": ["Dembi Dollo", "Nekemete"],
    "Nekemete": ["Gimbi", "Ambo", "Bedelle"],
    "Bedelle": ["Nekemete", "Jimma", "Gore"],
    "Gore": ["Bedelle", "Gambella", "Tepi"],
    "Gambella": ["Gore", "Dembi Dollo"],
    "Tepi": ["Gore", "Mezan Teferi", "Bonga"],
    "Mezan Teferi": ["Tepi", "Bonga"],
    "Bonga": ["Mezan Teferi", "Tepi", "Jimma", "Dawro"],
    "Jimma": ["Bonga", "Bedelle", "Wolkite"],
    "Wolkite": ["Jimma", "Worabe", "Ambo"],
    "Ambo": ["Wolkite", "Nekemete", "Addis Ababa"],
    "Addis Ababa": ["Ambo", "Debre Birhan", "Adama"],
    "Debre Dirhan": ["Addis Ababa"],
    "Adama": ["Addis Ababa", "Matahara", "Assella", "Batu"],
    "Batu": ["Adama", "Buta Jirra", "Shashemene"],
    "Buta Jirra": ["Batu", "Worabe"],
    "Worabe": ["Buta Jirra", "Wolkite", "Hossana"],
    "Hossana": ["Worabe", "Shashemene", "Wolaita Sodo"],
    "Wolaita Sodo": ["Hossana", "Dawro", "Arba Minch"],
    "Arba Minch": ["Wolaita Sodo"],
    "Dawro": ["Wolaita Sodo", "Bonga"],
    "Shashemene": ["Hossana", "Hawassa", "Batu", "Dodolla"],
    "Hawassa": ["Shashemene", "Dilla"],
    "Dilla": ["Hawassa"],
    "Dodolla": ["Shashemene", "Assasa", "Bale"],
    "Bale": ["Dodolla", "Goba", "Sof Oumer"],
    "Goba": ["Bale", "Dega Habur", "Sof Oumer"],
    "Sof Oumer": ["Goba", "Bale", "Kebri Dehar"],
    "Kebri Dehar": ["SOf Oumer", "Dega Habur", "Gode"],
    "Gode": ["Kebri Dehar"],
    "Dega Habur": ["Goba", "Kebri Dehar", "Jigjiga"],
    "Jigjiga": ["Dega Habur", "Babile"],
    "Babile": ["Jigjiga", "Harar"],
    "Harar": ["Babile", "Dire Dawa"],
    "Dire Dawa": ["Harar", "Chiro"],
    "Chiro": ["Dire Dawa", "Awash"],
    "Awash": ["Chiro", "Matahara"],
    "Matahara": ["Awash", "Adama"],
    "Assella": ["Adama", "Assasa"],
    "Assasa": ["Assella", "Dodola"],

}